
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrchywnyoqcwwfkxzsja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyY2h5d255b3Fjd3dma3h6c2phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMDk1MzksImV4cCI6MjA2MTU4NTUzOX0.mmi8EHZnmbFg9m7DJEOf0izPHPOLU6Qo8PrbY9a38Fg";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true, // Keep session alive
      autoRefreshToken: true, // Auto-refresh tokens
      detectSessionInUrl: false, // Disable URL detection to prevent race conditions
      storage: localStorage // Explicitly use localStorage for session storage
    }
  }
);

// Debug session status on client init
console.log("[Supabase Client] Initialized");
